apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wisecow-route
  namespace: default
spec:
  parentRefs:
  - name: wisecow-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: wisecow
      port: 80
