apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- gateway.yaml
- httproute.yaml
- tls.yaml
- cert-manager.yaml
- envoy-gateway.yaml
- envoy-gatewayclass.yaml

images:
- name: ghcr.io/vivekanandan-ks/wisecow-ksv-challenge
  newName: ghcr.io/vivekanandan-ks/wisecow-ksv-challenge
  newTag: main-9ce5da194959563e5715f3b586f1a86b415ed756
