# You must create this secret using:
# kubectl create secret docker-registry ghcr-secret \
#  --docker-server=ghcr.io \
#  --docker-username=<YOUR_USERNAME> \
#  --docker-password=<YOUR_GITHUB_PAT> \
#  --dry-run=client -o yaml > k8s/registry-secret.yaml
#
# Note: I am providing a template below.
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_CONFIG>
